kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
name: test
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 3001
charts:
  - name: test
    path: helm/test
    apps:
      - name: worker
        dockerfile: worker.Dockerfile
      - name: server
        dockerfile: server.Dockerfile
resources:
  - test/cluster/secret.yaml
