version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests
          command: |
            go test -coverprofile $TEST_RESULTS/cover.out -race ./...
            go tool cover -html=$TEST_RESULTS/cover.out -o $TEST_RESULTS/cover.html

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
